/*-------------------------------------------------------------------------+
|                                                                          |
| Copyright 2005-2011 The ConQAT Project                                   |
|                                                                          |
| Licensed under the Apache License, Version 2.0 (the "License");          |
| you may not use this file except in compliance with the License.         |
| You may obtain a copy of the License at                                  |
|                                                                          |
|    http://www.apache.org/licenses/LICENSE-2.0                            |
|                                                                          |
| Unless required by applicable law or agreed to in writing, software      |
| distributed under the License is distributed on an "AS IS" BASIS,        |
| WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. |
| See the License for the specific language governing permissions and      |
| limitations under the License.                                           |
+-------------------------------------------------------------------------*/
package org.conqat.engine.dotnet.ila.xml;

/**
 * Enumeration of the XML attributes of the IL-XML format.
 * 
 * @author Elmar Juergens
 * @author $Author: streitel $
 * 
 * @version $Revision: 50995 $
 * @ConQAT.Rating GREEN Hash: 36E7DDE24335C32227D0E0804EC5905E
 */
public enum EIlaXmlAttribute {

	/** Name of a type */
	Type,

	/** Name of a member */
	Name,

	/** Visibility of a member */
	Visibility,

	/** Metadata token of a member */
	Token,

	/** Type of a member (i.e. constructor, method, ...) */
	MemberType,

	/** Number of IL statements of the implementation of the member's body. */
	NumILStmts,

	/**
	 * Indicates that code unit has been generated by the compiler and has no
	 * counterpart in the source code.
	 */
	Synthetic,

	/** Indicates whether a type is a class, interface, struct, ... */
	DeclType,

	/** Indicates whether type is abstract */
	IsAbstract,

	/** Description of assembly */
	Assembly,

	/** IL Statements of method body */
	BodyZip,

	/** Raw name as contained in IL */
	RawName,

	/** Plain name without type information etc. */
	ShortName,

	/** Method return type. */
	ReturnType,

	/** Generic method parameter sting */
	GenericParameters
}